# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the main branch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run pwd
      run: pwd
      
    - name: Run ls -al
      run: ls -al
    # The type of runner that the job will run on

